### ISSUE TITLE
Fix typos in writing ringwormGO

### ISSUE THREAD

**Issue by Andrej123456789** [ringwormGO-organization/DiscordBot-v2#6]
@ElectroBoy404NotFound You made several typos while making `/about` command.
First two typos are about **ringwormGO** and last one is about GitHub, G and H are capital letters, and ringwormGO is all small except letter G and letter O.

[Line 8](https://github.com/ringwormGO-organization/DiscordBot-v2/blob/main/src/org/ringwormgo/discordbotv2/event/commands/slashcommands/commands/AboutSlashCommand.java#L8)

[Line 9](https://github.com/ringwormGO-organization/DiscordBot-v2/blob/main/src/org/ringwormgo/discordbotv2/event/commands/slashcommands/commands/AboutSlashCommand.java#L9)

[Line 10](https://github.com/ringwormGO-organization/DiscordBot-v2/blob/main/src/org/ringwormgo/discordbotv2/event/commands/slashcommands/commands/AboutSlashCommand.java#L10)

**Comment by ElectroBoy404NotFound** [comment]
Ok, I'm going to fix them today by 9:00 pm IST

**Comment by ElectroBoy404NotFound** [comment]
I fixed it in #8
